// Code generated by internal/gen. DO NOT EDIT.

package require

import (
	"github.com/stretchr/testify/require"
)

// Contains asserts that the specified string, list(array, slice...) or map contains the
// specified substring or element.
func (Assertions[T]) Contains(contains interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Contains(t, actual, contains, declaredAt(loc, msgAndArgs, called)...)
	}
}

// ElementsMatch asserts that the specified listA(array, slice...) is equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should match.
func (Assertions[T]) ElementsMatch(listB T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.ElementsMatch(t, actual, listB, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Empty asserts that the given value is "empty".
func (Assertions[T]) Empty(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Empty(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Equal asserts that two objects are equal.
func (Assertions[T]) Equal(expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Equal(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// EqualExportedValues asserts that the types of two objects are equal and their public
// fields are also equal. This is useful for comparing structs that have private fields
// that could potentially differ.
func (Assertions[T]) EqualExportedValues(expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.EqualExportedValues(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// EqualValues asserts that two objects are equal or convertible to the larger
// type and equal.
func (Assertions[T]) EqualValues(expected interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.EqualValues(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Exactly asserts that two objects are equal in value and type.
func (Assertions[T]) Exactly(expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Exactly(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Greater asserts that the first element is greater than the second
func (Assertions[T]) Greater(e2 T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Greater(t, actual, e2, declaredAt(loc, msgAndArgs, called)...)
	}
}

// GreaterOrEqual asserts that the first element is greater than or equal to the second
func (Assertions[T]) GreaterOrEqual(e2 T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.GreaterOrEqual(t, actual, e2, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Implements asserts that an object is implemented by the specified interface.
func (Assertions[T]) Implements(interfaceObject interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Implements(t, interfaceObject, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InDelta asserts that the two numerals are within delta of each other.
func (Assertions[T]) InDelta(expected interface{}, delta float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InDelta(t, expected, actual, delta, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InDeltaMapValues is the same as InDelta, but it compares all values between two maps. Both maps must have exactly the same keys.
func (Assertions[T]) InDeltaMapValues(expected interface{}, delta float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InDeltaMapValues(t, expected, actual, delta, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InDeltaSlice is the same as InDelta, except it compares two slices.
func (Assertions[T]) InDeltaSlice(expected interface{}, delta float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InDeltaSlice(t, expected, actual, delta, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InEpsilon asserts that expected and actual have a relative error less than epsilon
func (Assertions[T]) InEpsilon(expected interface{}, epsilon float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InEpsilon(t, expected, actual, epsilon, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InEpsilonSlice is the same as InEpsilon, except it compares each value from two slices.
func (Assertions[T]) InEpsilonSlice(expected interface{}, epsilon float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InEpsilonSlice(t, expected, actual, epsilon, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsDecreasing asserts that the collection is decreasing
func (Assertions[T]) IsDecreasing(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsDecreasing(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsIncreasing asserts that the collection is increasing
func (Assertions[T]) IsIncreasing(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsIncreasing(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsNonDecreasing asserts that the collection is not decreasing
func (Assertions[T]) IsNonDecreasing(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsNonDecreasing(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsNonIncreasing asserts that the collection is not increasing
func (Assertions[T]) IsNonIncreasing(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsNonIncreasing(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsNotType asserts that the specified objects are not of the same type.
func (Assertions[T]) IsNotType(theType interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsNotType(t, theType, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsType asserts that the specified objects are of the same type.
func (Assertions[T]) IsType(expectedType interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsType(t, expectedType, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Len asserts that the specified object has specific length.
// Len also fails if the object has a type that len() not accept.
func (Assertions[T]) Len(length int, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Len(t, actual, length, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Less asserts that the first element is less than the second
func (Assertions[T]) Less(e2 T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Less(t, actual, e2, declaredAt(loc, msgAndArgs, called)...)
	}
}

// LessOrEqual asserts that the first element is less than or equal to the second
func (Assertions[T]) LessOrEqual(e2 T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.LessOrEqual(t, actual, e2, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Negative asserts that the specified element is negative
func (Assertions[T]) Negative(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Negative(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Nil asserts that the specified object is nil.
func (Assertions[T]) Nil(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Nil(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotContains asserts that the specified string, list(array, slice...) or map does NOT contain the
// specified substring or element.
func (Assertions[T]) NotContains(contains interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotContains(t, actual, contains, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotElementsMatch asserts that the specified listA(array, slice...) is NOT equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should not match.
// This is an inverse of ElementsMatch.
func (Assertions[T]) NotElementsMatch(listB T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotElementsMatch(t, actual, listB, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotEmpty asserts that the specified object is NOT [Empty].
func (Assertions[T]) NotEmpty(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotEmpty(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotEqual asserts that the specified values are NOT equal.
func (Assertions[T]) NotEqual(expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotEqual(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotEqualValues asserts that two objects are not equal even when converted to the same type
func (Assertions[T]) NotEqualValues(expected interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotEqualValues(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotImplements asserts that an object does not implement the specified interface.
func (Assertions[T]) NotImplements(interfaceObject interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotImplements(t, interfaceObject, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotNil asserts that the specified object is not nil.
func (Assertions[T]) NotNil(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotNil(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotRegexp asserts that a specified regexp does not match a string.
func (Assertions[T]) NotRegexp(rx interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotRegexp(t, rx, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotSame asserts that two pointers do not reference the same object.
func (Assertions[T]) NotSame(expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotSame(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotSubset asserts that the list (array, slice, or map) does NOT contain all
// elements given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
func (Assertions[T]) NotSubset(subset interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotSubset(t, actual, subset, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotZero asserts that i is not the zero value for its type.
func (Assertions[T]) NotZero(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotZero(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Positive asserts that the specified element is positive
func (Assertions[T]) Positive(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Positive(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Regexp asserts that a specified regexp matches a string.
func (Assertions[T]) Regexp(rx interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Regexp(t, rx, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Same asserts that two pointers reference the same object.
func (Assertions[T]) Same(expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Same(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Subset asserts that the list (array, slice, or map) contains all elements
// given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
func (Assertions[T]) Subset(subset interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Subset(t, actual, subset, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Zero asserts that i is the zero value for its type.
func (Assertions[T]) Zero(msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Zero(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}
