// Code generated by internal/gen. DO NOT EDIT.

package require

import (
	"net/http"
	"net/url"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Contains asserts that the specified string, list(array, slice...) or map contains the
// specified substring or element.
func Contains[T any](contains interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Contains(t, actual, contains, declaredAt(loc, msgAndArgs, called)...)
	}
}

// DirExists checks whether a directory exists in the given path. It also fails
// if the path is a file rather a directory or there is an error checking whether it exists.
func DirExists(msgAndArgs ...any) GenericAssertionFunc[string] {
	loc := loc()
	return func(t TestingT, actual string, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.DirExists(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// ElementsMatch asserts that the specified listA(array, slice...) is equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should match.
func ElementsMatch[T any](listB T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.ElementsMatch(t, actual, listB, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Empty asserts that the given value is "empty".
func Empty[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Empty(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Equal asserts that two objects are equal.
func Equal[T any](expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Equal(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// EqualError asserts that a function returned a non-nil error (i.e. an error)
// and that it is equal to the provided error.
func EqualError(errString string, msgAndArgs ...any) GenericAssertionFunc[error] {
	loc := loc()
	return func(t TestingT, actual error, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.EqualError(t, actual, errString, declaredAt(loc, msgAndArgs, called)...)
	}
}

// EqualExportedValues asserts that the types of two objects are equal and their public
// fields are also equal. This is useful for comparing structs that have private fields
// that could potentially differ.
func EqualExportedValues[T any](expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.EqualExportedValues(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// EqualValues asserts that two objects are equal or convertible to the larger
// type and equal.
func EqualValues[T any](expected interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.EqualValues(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Error asserts that a function returned a non-nil error (ie. an error).
func Error(msgAndArgs ...any) GenericAssertionFunc[error] {
	loc := loc()
	return func(t TestingT, actual error, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Error(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// ErrorAs asserts that at least one of the errors in err's chain matches target, and if so, sets target to that error value.
// This is a wrapper for errors.As.
func ErrorAs(target interface{}, msgAndArgs ...any) GenericAssertionFunc[error] {
	loc := loc()
	return func(t TestingT, actual error, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.ErrorAs(t, actual, target, declaredAt(loc, msgAndArgs, called)...)
	}
}

// ErrorContains asserts that a function returned a non-nil error (i.e. an
// error) and that the error contains the specified substring.
func ErrorContains(contains string, msgAndArgs ...any) GenericAssertionFunc[error] {
	loc := loc()
	return func(t TestingT, actual error, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.ErrorContains(t, actual, contains, declaredAt(loc, msgAndArgs, called)...)
	}
}

// ErrorIs asserts that at least one of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func ErrorIs(target error, msgAndArgs ...any) GenericAssertionFunc[error] {
	loc := loc()
	return func(t TestingT, actual error, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.ErrorIs(t, actual, target, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Exactly asserts that two objects are equal in value and type.
func Exactly[T any](expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Exactly(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// False asserts that the specified value is false.
func False(msgAndArgs ...any) GenericAssertionFunc[bool] {
	loc := loc()
	return func(t TestingT, actual bool, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.False(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// FileExists checks whether a file exists in the given path. It also fails if
// the path points to a directory or there is an error when trying to check the file.
func FileExists(msgAndArgs ...any) GenericAssertionFunc[string] {
	loc := loc()
	return func(t TestingT, actual string, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.FileExists(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Greater asserts that the first element is greater than the second
func Greater[T any](e2 T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Greater(t, actual, e2, declaredAt(loc, msgAndArgs, called)...)
	}
}

// GreaterOrEqual asserts that the first element is greater than or equal to the second
func GreaterOrEqual[T any](e2 T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.GreaterOrEqual(t, actual, e2, declaredAt(loc, msgAndArgs, called)...)
	}
}

// HTTPBodyContains asserts that a specified handler returns a
// body that contains a string.
func HTTPBodyContains(method string, url string, values url.Values, str interface{}, msgAndArgs ...any) GenericAssertionFunc[http.HandlerFunc] {
	loc := loc()
	return func(t TestingT, actual http.HandlerFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.HTTPBodyContains(t, actual, method, url, values, str, declaredAt(loc, msgAndArgs, called)...)
	}
}

// HTTPBodyNotContains asserts that a specified handler returns a
// body that does not contain a string.
func HTTPBodyNotContains(method string, url string, values url.Values, str interface{}, msgAndArgs ...any) GenericAssertionFunc[http.HandlerFunc] {
	loc := loc()
	return func(t TestingT, actual http.HandlerFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.HTTPBodyNotContains(t, actual, method, url, values, str, declaredAt(loc, msgAndArgs, called)...)
	}
}

// HTTPError asserts that a specified handler returns an error status code.
func HTTPError(method string, url string, values url.Values, msgAndArgs ...any) GenericAssertionFunc[http.HandlerFunc] {
	loc := loc()
	return func(t TestingT, actual http.HandlerFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.HTTPError(t, actual, method, url, values, declaredAt(loc, msgAndArgs, called)...)
	}
}

// HTTPRedirect asserts that a specified handler returns a redirect status code.
func HTTPRedirect(method string, url string, values url.Values, msgAndArgs ...any) GenericAssertionFunc[http.HandlerFunc] {
	loc := loc()
	return func(t TestingT, actual http.HandlerFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.HTTPRedirect(t, actual, method, url, values, declaredAt(loc, msgAndArgs, called)...)
	}
}

// HTTPStatusCode asserts that a specified handler returns a specified status code.
func HTTPStatusCode(method string, url string, values url.Values, statuscode int, msgAndArgs ...any) GenericAssertionFunc[http.HandlerFunc] {
	loc := loc()
	return func(t TestingT, actual http.HandlerFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.HTTPStatusCode(t, actual, method, url, values, statuscode, declaredAt(loc, msgAndArgs, called)...)
	}
}

// HTTPSuccess asserts that a specified handler returns a success status code.
func HTTPSuccess(method string, url string, values url.Values, msgAndArgs ...any) GenericAssertionFunc[http.HandlerFunc] {
	loc := loc()
	return func(t TestingT, actual http.HandlerFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.HTTPSuccess(t, actual, method, url, values, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Implements asserts that an object is implemented by the specified interface.
func Implements[T any](interfaceObject interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Implements(t, interfaceObject, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InDelta asserts that the two numerals are within delta of each other.
func InDelta[T any](expected interface{}, delta float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InDelta(t, expected, actual, delta, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InDeltaMapValues is the same as InDelta, but it compares all values between two maps. Both maps must have exactly the same keys.
func InDeltaMapValues[T any](expected interface{}, delta float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InDeltaMapValues(t, expected, actual, delta, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InDeltaSlice is the same as InDelta, except it compares two slices.
func InDeltaSlice[T any](expected interface{}, delta float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InDeltaSlice(t, expected, actual, delta, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InEpsilon asserts that expected and actual have a relative error less than epsilon
func InEpsilon[T any](expected interface{}, epsilon float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InEpsilon(t, expected, actual, epsilon, declaredAt(loc, msgAndArgs, called)...)
	}
}

// InEpsilonSlice is the same as InEpsilon, except it compares each value from two slices.
func InEpsilonSlice[T any](expected interface{}, epsilon float64, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.InEpsilonSlice(t, expected, actual, epsilon, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsDecreasing asserts that the collection is decreasing
func IsDecreasing[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsDecreasing(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsIncreasing asserts that the collection is increasing
func IsIncreasing[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsIncreasing(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsNonDecreasing asserts that the collection is not decreasing
func IsNonDecreasing[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsNonDecreasing(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsNonIncreasing asserts that the collection is not increasing
func IsNonIncreasing[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsNonIncreasing(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsNotType asserts that the specified objects are not of the same type.
func IsNotType[T any](theType interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsNotType(t, theType, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// IsType asserts that the specified objects are of the same type.
func IsType[T any](expectedType interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.IsType(t, expectedType, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// JSONEq asserts that two JSON strings are equivalent.
func JSONEq(expected string, msgAndArgs ...any) GenericAssertionFunc[string] {
	loc := loc()
	return func(t TestingT, actual string, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.JSONEq(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Len asserts that the specified object has specific length.
// Len also fails if the object has a type that len() not accept.
func Len[T any](length int, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Len(t, actual, length, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Less asserts that the first element is less than the second
func Less[T any](e2 T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Less(t, actual, e2, declaredAt(loc, msgAndArgs, called)...)
	}
}

// LessOrEqual asserts that the first element is less than or equal to the second
func LessOrEqual[T any](e2 T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.LessOrEqual(t, actual, e2, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Negative asserts that the specified element is negative
func Negative[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Negative(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Nil asserts that the specified object is nil.
func Nil[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Nil(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NoDirExists checks whether a directory does not exist in the given path.
// It fails if the path points to an existing _directory_ only.
func NoDirExists(msgAndArgs ...any) GenericAssertionFunc[string] {
	loc := loc()
	return func(t TestingT, actual string, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NoDirExists(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NoError asserts that a function returned a nil error (ie. no error).
func NoError(msgAndArgs ...any) GenericAssertionFunc[error] {
	loc := loc()
	return func(t TestingT, actual error, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NoError(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NoFileExists checks whether a file does not exist in a given path. It fails
// if the path points to an existing _file_ only.
func NoFileExists(msgAndArgs ...any) GenericAssertionFunc[string] {
	loc := loc()
	return func(t TestingT, actual string, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NoFileExists(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotContains asserts that the specified string, list(array, slice...) or map does NOT contain the
// specified substring or element.
func NotContains[T any](contains interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotContains(t, actual, contains, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotElementsMatch asserts that the specified listA(array, slice...) is NOT equal to specified
// listB(array, slice...) ignoring the order of the elements. If there are duplicate elements,
// the number of appearances of each of them in both lists should not match.
// This is an inverse of ElementsMatch.
func NotElementsMatch[T any](listB T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotElementsMatch(t, actual, listB, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotEmpty asserts that the specified object is NOT [Empty].
func NotEmpty[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotEmpty(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotEqual asserts that the specified values are NOT equal.
func NotEqual[T any](expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotEqual(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotEqualValues asserts that two objects are not equal even when converted to the same type
func NotEqualValues[T any](expected interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotEqualValues(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotErrorAs asserts that none of the errors in err's chain matches target,
// but if so, sets target to that error value.
func NotErrorAs(target interface{}, msgAndArgs ...any) GenericAssertionFunc[error] {
	loc := loc()
	return func(t TestingT, actual error, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotErrorAs(t, actual, target, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotErrorIs asserts that none of the errors in err's chain matches target.
// This is a wrapper for errors.Is.
func NotErrorIs(target error, msgAndArgs ...any) GenericAssertionFunc[error] {
	loc := loc()
	return func(t TestingT, actual error, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotErrorIs(t, actual, target, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotImplements asserts that an object does not implement the specified interface.
func NotImplements[T any](interfaceObject interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotImplements(t, interfaceObject, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotNil asserts that the specified object is not nil.
func NotNil[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotNil(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotPanics asserts that the code inside the specified PanicTestFunc does NOT panic.
func NotPanics(msgAndArgs ...any) GenericAssertionFunc[assert.PanicTestFunc] {
	loc := loc()
	return func(t TestingT, actual assert.PanicTestFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotPanics(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotRegexp asserts that a specified regexp does not match a string.
func NotRegexp[T any](rx interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotRegexp(t, rx, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotSame asserts that two pointers do not reference the same object.
func NotSame[T any](expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotSame(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotSubset asserts that the list (array, slice, or map) does NOT contain all
// elements given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
func NotSubset[T any](subset interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotSubset(t, actual, subset, declaredAt(loc, msgAndArgs, called)...)
	}
}

// NotZero asserts that i is not the zero value for its type.
func NotZero[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.NotZero(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Panics asserts that the code inside the specified PanicTestFunc panics.
func Panics(msgAndArgs ...any) GenericAssertionFunc[assert.PanicTestFunc] {
	loc := loc()
	return func(t TestingT, actual assert.PanicTestFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Panics(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// PanicsWithError asserts that the code inside the specified PanicTestFunc
// panics, and that the recovered panic value is an error that satisfies the
// EqualError comparison.
func PanicsWithError(errString string, msgAndArgs ...any) GenericAssertionFunc[assert.PanicTestFunc] {
	loc := loc()
	return func(t TestingT, actual assert.PanicTestFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.PanicsWithError(t, errString, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// PanicsWithValue asserts that the code inside the specified PanicTestFunc panics, and that
// the recovered panic value equals the expected panic value.
func PanicsWithValue(expected interface{}, msgAndArgs ...any) GenericAssertionFunc[assert.PanicTestFunc] {
	loc := loc()
	return func(t TestingT, actual assert.PanicTestFunc, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.PanicsWithValue(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Positive asserts that the specified element is positive
func Positive[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Positive(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Regexp asserts that a specified regexp matches a string.
func Regexp[T any](rx interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Regexp(t, rx, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Same asserts that two pointers reference the same object.
func Same[T any](expected T, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Same(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Subset asserts that the list (array, slice, or map) contains all elements
// given in the subset (array, slice, or map).
// Map elements are key-value pairs unless compared with an array or slice where
// only the map key is evaluated.
func Subset[T any](subset interface{}, msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Subset(t, actual, subset, declaredAt(loc, msgAndArgs, called)...)
	}
}

// True asserts that the specified value is true.
func True(msgAndArgs ...any) GenericAssertionFunc[bool] {
	loc := loc()
	return func(t TestingT, actual bool, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.True(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// WithinDuration asserts that the two times are within duration delta of each other.
func WithinDuration(expected time.Time, delta time.Duration, msgAndArgs ...any) GenericAssertionFunc[time.Time] {
	loc := loc()
	return func(t TestingT, actual time.Time, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.WithinDuration(t, expected, actual, delta, declaredAt(loc, msgAndArgs, called)...)
	}
}

// WithinRange asserts that a time is within a time range (inclusive).
func WithinRange(start time.Time, end time.Time, msgAndArgs ...any) GenericAssertionFunc[time.Time] {
	loc := loc()
	return func(t TestingT, actual time.Time, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.WithinRange(t, actual, start, end, declaredAt(loc, msgAndArgs, called)...)
	}
}

// YAMLEq asserts that the first documents in the two YAML strings are equivalent.
func YAMLEq(expected string, msgAndArgs ...any) GenericAssertionFunc[string] {
	loc := loc()
	return func(t TestingT, actual string, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.YAMLEq(t, expected, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}

// Zero asserts that i is the zero value for its type.
func Zero[T any](msgAndArgs ...any) GenericAssertionFunc[T] {
	loc := loc()
	return func(t TestingT, actual T, called ...any) {
		if h, ok := t.(tHelper); ok {
			h.Helper()
		}
		require.Zero(t, actual, declaredAt(loc, msgAndArgs, called)...)
	}
}
